# Generated by Django 3.2.2 on 2021-06-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTrip', '0007_auto_20210607_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelBooking',
            new_name='Booking',
        ),
    ]
