# Generated by Django 3.2.2 on 2021-06-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTrip', '0008_rename_hotelbooking_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
