# Generated by Django 3.2.2 on 2021-06-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTrip', '0009_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
